package com.example.notKahoot.model

import android.os.Parcelable
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize

@Parcelize
@Entity(tableName = "quiz_table")
data class QuizModel(
    @PrimaryKey(autoGenerate = true)
    val id: Int, // <- 'id' is the primary key which will be autogenerated by the Room library.
    @ColumnInfo
    var quizTitle: String,
    @ColumnInfo
    var totalQuestions: Long
): Parcelable
